# Generated by Django 4.2.4 on 2023-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0002_alter_customeruser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
