# Generated by Django 4.2.4 on 2023-08-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.productcategory')),
            ],
        ),
    ]
