# Generated by Django 4.2.4 on 2023-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_shipping_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=30),
        ),
    ]
