# Generated by Django 4.2.4 on 2023-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'Canceled'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=30),
        ),
    ]
