# Generated by Django 4.1 on 2023-07-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0002_alter_productcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
