# Generated by Django 4.1 on 2023-07-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0003_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
