# Generated by Django 4.1 on 2023-07-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0005_order_orderitem_order_items_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
